
POST http://localhost:3222/api
Content-Type: application/json

{
  "name": "Jose Josue",
  "comment": "Otro comentario de prueba.",
  "detail": "details1"
}

###
GET http://localhost:3222/api

###

PUT http://localhost:3222/api/0
Content-Type: application/json

{
  "name": "Juan Pérez",
  "comment": "Este es un comentario actualizado.",
  "detail": "Detalles actualizados sobre el comentario."
}

###

DELETE http://localhost:3222/api/0