
POST http://localhost:3222/api
Content-Type: application/json

{
  "name": "pedro Pedraza",
  "comment": "El mas picante del condado.",
  "detail": "details2", 
  "urlPicture" : "https://res.cloudinary.com/dxbldbqgb/image/upload/v1738541262/avatar_tzpr4l.webp"
}

###
GET http://localhost:3222/api
Content-Type: application/json

###

PUT http://localhost:3222/api/0
Content-Type: application/json

{
  "name": "Juan Pérez",
  "comment": "Este es un comentario actualizado.",
  "detail": "Detalles actualizados sobre el comentario.", 
  "urlPicture" : "https://res.cloudinary.com/dxbldbqgb/image/upload/v1738541262/avatar_tzpr4l.webp"
}

###

DELETE http://localhost:3222/api/0